# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Harusame64.pictkura
PackageVersion: 0.2.9
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.17134.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ReleaseDate: 2026-09-27
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Harusame64/pictkura/releases/download/v0.2.9/pictkura_0.2.9_x64-setup.exe
    InstallerSha256: F596A9CBCF420201EC1F3F3DF708F7D1A5900532A9E94A6F35ADE760EFC28B23
    AppsAndFeaturesEntries:
      - DisplayName: pictkura
        DisplayVersion: 0.2.9
        Publisher: Harusame64
        ProductCode: pictkura
ManifestType: installer
ManifestVersion: 1.9.0
